// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzmvdexqkepwtxuhrogk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6bXZkZXhxa2Vwd3R4dWhyb2drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MjAzOTgsImV4cCI6MjA2OTA5NjM5OH0.cZr6nPpdol5vgX3-_bEEyVJ3LTtaMfR8DgCfIdEc2QI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});